name: patient
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  flutter_credit_card: ^3.0.1
  flutter_svg: ^1.0.3
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.2
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  date_picker_timeline: ^1.2.1
  fluttertoast: ^8.0.7
  table_calendar: ^3.0.1
  country_calling_code_picker: ^2.0.0
  url_launcher: ^6.0.3
  firebase_auth: ^3.3.13
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  cloud_firestore: ^3.1.11
  http: ^0.13.1
  flutter_quill: ^4.1.1
  swipedetector: ^1.2.0
  share: ^2.0.4
  flutter_downloader: ^1.6.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  platform: ^3.1.0
  flutter_icons: ^1.1.0
  multi_select_flutter: ^4.0.0
  flutter_braintree: ^2.3.1
  geolocator: ^8.2.1
  flutter_geocoder: ^0.2.2-nullsafety
  google_maps_flutter: ^2.1.7
  pdf: ^3.1.0
  open_file: ^3.1.0
  flutter_absolute_path: ^1.0.6
  flutter_secure_storage: ^5.0.2
  logger: ^1.1.0
  file_picker_cross: ^4.6.0
  animated_splash_screen: ^1.3.0
  lottie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/CM Sans Serif.ttf

    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
